# Generated by Django 3.2.5 on 2021-11-21 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=35, verbose_name='Ваше ФИО')),
                ('phone', models.CharField(max_length=25, verbose_name='Ваш телефон')),
                ('mail', models.CharField(max_length=30, verbose_name='Ваша электронная почта')),
                ('topic', models.CharField(max_length=80, verbose_name='Тема обращения')),
                ('full_text', models.TextField(max_length=5000, verbose_name='Опишите вашу тему обращения')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 21, 14, 57, 5, 971367))),
            ],
            options={
                'verbose_name': 'Обратная свзяь',
            },
        ),
    ]
