# Generated by Django 3.2.5 on 2021-08-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='full_text',
            field=models.CharField(max_length=2000, verbose_name='Опишите вашу тему обращения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.CharField(max_length=30, verbose_name='Ваша электронная почта'),
        ),
    ]
