# Generated by Django 3.2.5 on 2021-08-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210804_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='full_text',
            field=models.TextField(max_length=5000, verbose_name='Опишите вашу тему обращения'),
        ),
    ]
