# Generated by Django 3.2.5 on 2022-01-13 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 13, 10, 32, 32, 207102)),
        ),
    ]
