# Generated by Django 3.2.5 on 2021-11-13 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 13, 17, 51, 21, 18715)),
        ),
    ]
