# Generated by Django 3.2.5 on 2021-11-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_feedback_date'),
        ('contacts', '0015_alter_feedback_date'),
    ]

    operations = [
    ]
