# Generated by Django 3.2.5 on 2021-11-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=35, verbose_name='Ваше ФИО')),
                ('phone', models.CharField(max_length=25, verbose_name='Ваш телефон')),
                ('case_number', models.CharField(max_length=30, verbose_name='Номер вашего обращения')),
                ('topic', models.CharField(max_length=80, verbose_name='Тема обращения')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Не рекомендую.'), (2, '2 - Неудовлетворительно.'), (3, '3 - Могло быть лучше.'), (4, '4 - Хорошо, все понравилось.'), (5, '5 - Превосходно!.')])),
                ('full_text', models.TextField(max_length=5000, verbose_name='Опишите вашу тему обращения')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзывы',
            },
        ),
    ]
