# Generated by Django 3.2.5 on 2021-11-14 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=35, verbose_name='Ваше ФИО')),
                ('phone', models.CharField(max_length=25, verbose_name='Ваш телефон')),
                ('case_number', models.CharField(max_length=30, verbose_name='Номер вашего обращения')),
                ('topic', models.CharField(max_length=80, verbose_name='Тема обращения')),
                ('rate', models.PositiveSmallIntegerField(blank=True, choices=[(5, '5 - Превосходно!'), (4, '4 - Хорошо, все понравилось.'), (3, '3 - Могло быть лучше.'), (2, '2 - Неудовлетворительно.'), (1, '1 - Не рекомендую.')])),
                ('full_text', models.TextField(max_length=5000, verbose_name='Опишите вашу тему обращения')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Отзывы',
            },
        ),
    ]
