# Generated by Django 3.2.5 on 2021-11-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Не рекомендую.'), (2, '2 - Неудовлетворительно.'), (3, '3 - Могло быть лучше.'), (4, '4 - Хорошо, все понравилось.'), (5, '5 - Превосходно!')]),
        ),
    ]
