# Generated by Django 3.2.5 on 2021-11-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
