# Generated by Django 3.2.5 on 2021-11-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rate',
            field=models.PositiveIntegerField(choices=[('5 - Превосходно!', 5), ('4 - Хорошо, все понравилось.', 4), ('3 - Могло быть лучше.', 3), ('2 - Неудовлетворительно.', 2), ('1 - Не рекомендую.', 1)]),
        ),
    ]
