# Generated by Django 3.2.5 on 2021-11-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_acc_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc',
            name='created_at',
        ),
    ]
